language: python
python:
  - 2.7.9-3
  # - 3.3
before_install:
  # - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  # - chmod +x miniconda.sh
  # - ./miniconda.sh -b
  # - export PATH=/home/travis/miniconda/bin:$PATH
  # - conda update --yes conda
  # - conda install --yes python=$TRAVIS_PYTHON_VERSION libffi cffi readline pyparsing atlas numpy scipy matplotlib dateutil Pillow statsmodels
  # - conda install psycopg2
  # - pip install --upgrade pip
  - sudo apt-get install -y python-dev build-essential
  - sudo apt-get install -y libreadline6 libreadline6-dev libreadline-dev libmemcached-dev zlib1g-dev libssl-dev
  - sudo apt-get install -y libncurses5 libncurses5-dev libffi-dev
install:
  - "sudo pip install git+https://github.com/hobson/pybrain.git@master#egg=pybrain-0.3.3"
  - "sudo pip install git+https://github.com/hobson/pug-nlp.git@master#egg=pug-nlp-master"
  - sudo pip -H install --upgrade -r requirements.txt
script: 
  - cd totalgood
  - python manage.py migrate
  - python manage.py test --keepdb
notifications:
  email:
  - admin@totalgood.com
