# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('zip_file', models.FileField(null=True, upload_to=b'backups', blank=True)),
                ('backup_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('num_posts', models.IntegerField(default=0)),
                ('num_revisions', models.IntegerField(default=0)),
                ('num_reads', models.IntegerField(default=0)),
                ('num_fantastics', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-backup_at',),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(null=True, blank=True)),
                ('slug', models.CharField(max_length=800, editable=False, blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(default=b'Title', null=True, blank=True)),
                ('body', models.TextField(default=b'Body', null=True, blank=True)),
                ('title_html', models.TextField(null=True, editable=False, blank=True)),
                ('body_html', models.TextField(null=True, editable=False, blank=True)),
                ('description', models.TextField(null=True, blank=True)),
                ('post_type', models.IntegerField(choices=[(1, b'Big Quote'), (2, b'Photo with caption'), (3, b'Article and a Single Image'), (4, b'Article and a multiple images'), (5, b'Body with no real title')])),
                ('num_images', models.IntegerField(default=0)),
                ('permalink_path', models.CharField(max_length=500, null=True, editable=False, blank=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('dayone_post', models.BooleanField(default=False, editable=False)),
                ('dayone_posted', models.DateTimeField(null=True, editable=False, blank=True)),
                ('dayone_last_modified', models.DateTimeField(null=True, editable=False, blank=True)),
                ('dayone_last_rev', models.CharField(max_length=255, null=True, editable=False, blank=True)),
                ('dayone_image', models.ImageField(upload_to=b'dayone_images', null=True, verbose_name=b'Hero Image', blank=True)),
                ('dayone_image_url', models.TextField(null=True, blank=True)),
                ('dayone_image_blog_size_url', models.TextField(null=True, blank=True)),
                ('dayone_image_thumb_size_url', models.TextField(null=True, blank=True)),
                ('twitter_publish_intent', models.BooleanField(default=True)),
                ('twitter_include_image', models.BooleanField(default=True)),
                ('twitter_published', models.BooleanField(default=False, editable=False)),
                ('twitter_status_text', models.TextField(null=True, blank=True)),
                ('twitter_status_id', models.CharField(max_length=255, null=True, editable=False, blank=True)),
                ('twitter_retweets', models.IntegerField(default=0, null=True, blank=True)),
                ('twitter_favorites', models.IntegerField(default=0, null=True, blank=True)),
                ('facebook_publish_intent', models.BooleanField(default=True)),
                ('facebook_published', models.BooleanField(default=False, editable=False)),
                ('facebook_status_text', models.TextField(null=True, blank=True)),
                ('facebook_status_id', models.CharField(max_length=255, null=True, editable=False, blank=True)),
                ('facebook_likes', models.IntegerField(default=0, null=True, blank=True)),
                ('facebook_shares', models.IntegerField(default=0, null=True, blank=True)),
                ('facebook_comments', models.IntegerField(default=0, null=True, blank=True)),
                ('social_shares_customized', models.BooleanField(default=False)),
                ('email_publish_intent', models.BooleanField(default=False)),
                ('allow_private_viewing', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sort_datetime', models.DateTimeField(null=True, editable=False, blank=True)),
                ('published_at', models.DateTimeField(null=True, editable=False, blank=True)),
                ('written_on', models.DateTimeField(default=datetime.datetime(2015, 4, 16, 0, 52, 28, 411789), null=True, blank=True)),
                ('slug', models.CharField(max_length=800, verbose_name=b'url', blank=True)),
                ('dayone_id', models.CharField(max_length=255, unique=True, null=True, editable=False, blank=True)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ConceptImage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to=b'post_images', blank=True)),
                ('image_url', models.TextField(null=True, blank=True)),
                ('blog_size_url', models.TextField(null=True, blank=True)),
                ('thumb_size_url', models.TextField(null=True, blank=True)),
                ('post', models.ForeignKey(to='conceive.Concept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptRevision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(default=b'Title', null=True, blank=True)),
                ('body', models.TextField(default=b'Body', null=True, blank=True)),
                ('title_html', models.TextField(null=True, editable=False, blank=True)),
                ('body_html', models.TextField(null=True, editable=False, blank=True)),
                ('description', models.TextField(null=True, blank=True)),
                ('post_type', models.IntegerField(choices=[(1, b'Big Quote'), (2, b'Photo with caption'), (3, b'Article and a Single Image'), (4, b'Article and a multiple images'), (5, b'Body with no real title')])),
                ('num_images', models.IntegerField(default=0)),
                ('permalink_path', models.CharField(max_length=500, null=True, editable=False, blank=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('dayone_post', models.BooleanField(default=False, editable=False)),
                ('dayone_posted', models.DateTimeField(null=True, editable=False, blank=True)),
                ('dayone_last_modified', models.DateTimeField(null=True, editable=False, blank=True)),
                ('dayone_last_rev', models.CharField(max_length=255, null=True, editable=False, blank=True)),
                ('dayone_image', models.ImageField(upload_to=b'dayone_images', null=True, verbose_name=b'Hero Image', blank=True)),
                ('dayone_image_url', models.TextField(null=True, blank=True)),
                ('dayone_image_blog_size_url', models.TextField(null=True, blank=True)),
                ('dayone_image_thumb_size_url', models.TextField(null=True, blank=True)),
                ('twitter_publish_intent', models.BooleanField(default=True)),
                ('twitter_include_image', models.BooleanField(default=True)),
                ('twitter_published', models.BooleanField(default=False, editable=False)),
                ('twitter_status_text', models.TextField(null=True, blank=True)),
                ('twitter_status_id', models.CharField(max_length=255, null=True, editable=False, blank=True)),
                ('twitter_retweets', models.IntegerField(default=0, null=True, blank=True)),
                ('twitter_favorites', models.IntegerField(default=0, null=True, blank=True)),
                ('facebook_publish_intent', models.BooleanField(default=True)),
                ('facebook_published', models.BooleanField(default=False, editable=False)),
                ('facebook_status_text', models.TextField(null=True, blank=True)),
                ('facebook_status_id', models.CharField(max_length=255, null=True, editable=False, blank=True)),
                ('facebook_likes', models.IntegerField(default=0, null=True, blank=True)),
                ('facebook_shares', models.IntegerField(default=0, null=True, blank=True)),
                ('facebook_comments', models.IntegerField(default=0, null=True, blank=True)),
                ('social_shares_customized', models.BooleanField(default=False)),
                ('email_publish_intent', models.BooleanField(default=False)),
                ('allow_private_viewing', models.BooleanField(default=False)),
                ('revised_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-revised_at',),
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('premium_user', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=255, editable=False, blank=True)),
                ('blog_name', models.CharField(max_length=255, blank=True)),
                ('blog_domain', models.CharField(max_length=255, unique=True, null=True, blank=True)),
                ('blog_header', models.TextField(null=True, blank=True)),
                ('blog_footer', models.TextField(null=True, blank=True)),
                ('public_domain', models.BooleanField(default=False)),
                ('wikipedia_url', models.TextField(null=True, blank=True)),
                ('archive', models.BooleanField(default=False)),
                ('archive_name', models.CharField(max_length=255, editable=False, blank=True)),
                ('birthdate', models.DateField(null=True, blank=True)),
                ('deathdate', models.DateField(null=True, blank=True)),
                ('dropbox_access_token', models.CharField(max_length=255, null=True, blank=True)),
                ('dropbox_user_id', models.CharField(max_length=255, null=True, blank=True)),
                ('dropbox_url_state', models.CharField(max_length=255, null=True, blank=True)),
                ('dropbox_expire_date', models.DateTimeField(null=True, blank=True)),
                ('dropbox_dayone_folder_path', models.CharField(max_length=255, null=True, blank=True)),
                ('dropbox_dayone_entry_hash', models.CharField(max_length=255, null=True, blank=True)),
                ('dropbox_dayone_image_hash', models.CharField(max_length=255, null=True, blank=True)),
                ('last_dropbox_sync', models.DateTimeField(null=True, blank=True)),
                ('facebook_api_key', models.TextField(null=True, blank=True)),
                ('facebook_account_link', models.TextField(null=True, blank=True)),
                ('facebook_account_name', models.CharField(max_length=255, null=True, blank=True)),
                ('facebook_expire_date', models.DateTimeField(null=True, blank=True)),
                ('facebook_profile_picture_url', models.TextField(null=True, blank=True)),
                ('twitter_api_key', models.TextField(null=True, blank=True)),
                ('twitter_api_secret', models.TextField(null=True, blank=True)),
                ('twitter_full_name', models.CharField(max_length=255, null=True, blank=True)),
                ('twitter_account_name', models.CharField(max_length=255, null=True, blank=True)),
                ('twitter_expire_date', models.DateTimeField(null=True, blank=True)),
                ('twitter_profile_picture_url', models.TextField(null=True, blank=True)),
                ('user', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fantastic',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=500, null=True, blank=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('on', models.BooleanField(default=True)),
                ('post', models.ForeignKey(to='conceive.Concept')),
                ('reader', models.ForeignKey(blank=True, to='conceive.Contributor', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, null=True, editable=False, blank=True)),
                ('area', models.CharField(max_length=255, null=True, blank=True)),
                ('country', models.CharField(max_length=255, null=True, blank=True)),
                ('latitude', models.FloatField(null=True, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('time_zone', models.CharField(max_length=255, null=True, editable=False, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=500, null=True, blank=True)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(to='conceive.Concept')),
                ('reader', models.ForeignKey(blank=True, to='conceive.Contributor', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('old_url', models.CharField(max_length=600, null=True, blank=True)),
                ('new_url', models.CharField(max_length=600, null=True, blank=True)),
                ('author', models.ForeignKey(to='conceive.Contributor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('temp', models.FloatField(help_text=b'Current outdoor (shaded) temperature (float, deg C)', null=True, blank=True)),
                ('condition', models.CharField(help_text=b'Short weather condition description (str, categorical)', max_length=255, null=True, editable=False, blank=True)),
                ('icon', models.CharField(max_length=255, null=True, editable=False, blank=True)),
                ('pressure_mmm', models.IntegerField(null=True, blank=True)),
                ('relative_humidity', models.IntegerField(null=True, blank=True)),
                ('wind_bearing', models.IntegerField(null=True, blank=True)),
                ('wind_chill_c', models.IntegerField(null=True, blank=True)),
                ('wind_speed_kph', models.IntegerField(null=True, blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='conceptrevision',
            name='author',
            field=models.ForeignKey(to='conceive.Contributor'),
        ),
        migrations.AddField(
            model_name='conceptrevision',
            name='location',
            field=models.ForeignKey(to='conceive.Location', null=True),
        ),
        migrations.AddField(
            model_name='conceptrevision',
            name='post',
            field=models.ForeignKey(to='conceive.Concept'),
        ),
        migrations.AddField(
            model_name='conceptrevision',
            name='weather',
            field=models.ForeignKey(to='conceive.Weather', null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='author',
            field=models.ForeignKey(to='conceive.Contributor'),
        ),
        migrations.AddField(
            model_name='concept',
            name='location',
            field=models.ForeignKey(to='conceive.Location', null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='weather',
            field=models.ForeignKey(to='conceive.Weather', null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='author',
            field=models.ForeignKey(to='conceive.Contributor'),
        ),
        migrations.AddField(
            model_name='backup',
            name='author',
            field=models.ForeignKey(to='conceive.Contributor'),
        ),
    ]
